---

- name: install packages required for archive processing
  yum:
    name: "{{ yum_archive_packages }}"
    state: installed

- name: get vault binary
  unarchive:
    src: https://releases.hashicorp.com/vault/1.0.3/vault_1.0.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
